[package]
name = "apicentric"
version = "0.2.5"
description = "Toolkit for building, recording, and sharing mock APIs"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pmaojo/apicentric"
homepage = "https://apicentric.pelayomaojo.es"

[[module]]
name = "apicentric"
source = "target/wasm32-wasmer-wasi/release/apicentric.wasm"
abi = "wasi"
interfaces = { "wasi:http/proxy" = "0.2.0-rc-2023-10-18" }

[commands.start]
runner = "https://webc.org/runner/wasi/wasi-http-proxy"
annotations = { "wasi:http/proxy" = { "default" = true } }

[fs]
"/config" = "config"
"/services" = "services"
